services:
  # Main Bot - Personal & Group Chat
  omnik:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: omnik
    restart: unless-stopped
    user: "node"
    environment:
      - OMNI_TELEGRAM_BOT_TOKEN=${OMNI_TELEGRAM_BOT_TOKEN}
      - OMNI_AUTHORIZED_USER_ID=${OMNI_AUTHORIZED_USER_ID}
      - OMNI_TG_AUTH_CHAT_ID=${OMNI_TG_AUTH_CHAT_ID:-}
      - OMNI_ANTHROPIC_API_KEY=${OMNI_ANTHROPIC_API_KEY}
      - OMNI_USE_CLAUDE_SDK=true
      - OMNI_CLAUDE_MODEL=${OMNI_CLAUDE_MODEL:-sonnet}
      - OMNI_LOG_LEVEL=${OMNI_LOG_LEVEL:-INFO}
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
      - GIT_USER_NAME=${GIT_USER_NAME:-Omnik Bot}
      - GIT_USER_EMAIL=${GIT_USER_EMAIL:-bot@omnik.local}
    volumes:
      - workspace:/workspace
      - claude-home:/home/node
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - omnik-net
      - kb_network
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 256M

  # API Bot - Dedicated API Access
  omnik-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: omnik-api
    restart: unless-stopped
    user: "node"
    environment:
      - OMNI_TELEGRAM_BOT_TOKEN=${OMNI_API_BOT_TOKEN}
      - OMNI_AUTHORIZED_USER_ID=${OMNI_API_AUTHORIZED_USER_ID}
      - OMNI_TG_AUTH_CHAT_ID=${OMNI_API_AUTH_CHAT_ID:-}
      - OMNI_ANTHROPIC_API_KEY=${OMNI_ANTHROPIC_API_KEY}
      - OMNI_USE_CLAUDE_SDK=true
      - OMNI_CLAUDE_MODEL=${OMNI_CLAUDE_MODEL:-sonnet}
      - OMNI_LOG_LEVEL=${OMNI_LOG_LEVEL:-INFO}
      - OMNI_API_PORT=8080
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
      - GIT_USER_NAME=${GIT_USER_NAME:-Memnikai Bot}
      - GIT_USER_EMAIL=${GIT_USER_EMAIL:-bot@omnik.local}
    ports:
      - "8081:8080"
    volumes:
      - workspace:/workspace
      - claude-home:/home/node
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - omnik-net
      - kb_network
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 256M

networks:
  omnik-net:
    driver: bridge
  kb_network:
    external: true

volumes:
  workspace:
    driver: local
  claude-home:
    driver: local
