services:
  omnik:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: omnik
    restart: unless-stopped
    user: "node"
    environment:
      - OMNI_TELEGRAM_BOT_TOKEN=${OMNI_TELEGRAM_BOT_TOKEN}
      - OMNI_AUTHORIZED_USER_ID=${OMNI_AUTHORIZED_USER_ID}
      - OMNI_ANTHROPIC_API_KEY=${OMNI_ANTHROPIC_API_KEY}
      - OMNI_USE_CLAUDE_SDK=true
      - OMNI_CLAUDE_MODEL=sonnet
      - OMNI_LOG_LEVEL=${OMNI_LOG_LEVEL:-INFO}
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
      - GIT_USER_NAME=${GIT_USER_NAME:-Omnik Bot}
      - GIT_USER_EMAIL=${GIT_USER_EMAIL:-bot@omnik.local}
    volumes:
      - workspace:/workspace
      - claude-auth:/home/node/.claude
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - omnik-net
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 256M

networks:
  omnik-net:
    driver: bridge

volumes:
  workspace:
    driver: local
  claude-auth:
    driver: local
